export const profiles = [
  {
    name: 'Александр Александров',
    isAvailable: true,
    isFavorite: false,
    lastSeen: 'Сегодня',
    position: 'Дизайнер интерфейсов',
    graduated: 'октябрь 2020',
    experience: '3 года',
    stack: ['Figma', 'Adobe', 'Illustrator', 'CSS'],
    city: 'Москва',
    jobFormat: ['офис', 'удаленка', 'релокейт', 'полный день'],
  },
  {
    name: 'Александр Александров',
    isAvailable: false,
    isFavorite: false,
    lastSeen: 'Сегодня',
    position: 'Дизайнер интерфейсов',
    graduated: 'октябрь 2020',
    experience: '3 года',
    stack: ['Figma', 'Adobe', 'Illustrator', 'CSS'],
  },
  {
    name: 'Александр Александров',
    isAvailable: true,
    isFavorite: true,
    lastSeen: 'Сегодня',
    position: 'Дизайнер интерфейсов',
    graduated: 'октябрь 2020',
    experience: '3 года',
    stack: ['Figma', 'Adobe', 'Illustrator', 'CSS'],
  },
  {
    name: 'Александр Александров',
    isAvailable: true,
    isFavorite: false,
    lastSeen: 'Сегодня',
    position: 'Дизайнер интерфейсов',
    graduated: 'октябрь 2020',
    experience: '3 года',
    stack: ['Figma', 'Adobe', 'Illustrator', 'CSS'],
  },
  {
    name: 'Александр Александров',
    isAvailable: true,
    isFavorite: true,
    lastSeen: 'Сегодня',
    position: 'Дизайнер интерфейсов',
    graduated: 'октябрь 2020',
    experience: '3 года',
    stack: ['Figma', 'Adobe', 'Illustrator', 'CSS'],
  },
  {
    name: 'Александр Александров',
    isAvailable: false,
    isFavorite: false,
    lastSeen: 'Сегодня',
    position: 'Дизайнер интерфейсов',
    graduated: 'октябрь 2020',
    experience: '3 года',
    stack: ['Figma', 'Adobe', 'Illustrator', 'CSS'],
  },
];
